### ISSUE TITLE
Request: EF & CH: "East Falls Block Party" (Saturday, August 24, 11:00AM)

### ISSUE THREAD

**Issue by jessxu12** [metrophilly/docs.metrophilly.org#100]
Fill out event details (Usually comes from the #communications slack channel)

**TITLE:**
EF & CH: "East Falls Block Party" (Saturday, August 24, 11:00AM)

**COPY:**
"East Falls Block Party. Metro will be hosting our annual, end-of-summer event at the Falls Ridge Apartments (4349 Ridge Ave) on Saturday, August 24 at 11:00AM. If interested in volunteering for our potluck, delivering groceries, or setting up and cleaning up, please register at http://metrophilly.org/events. Please contact joshua@metrophilly.org with any questions."

**DUE DATE:**
on website by Sat 7/27 with registration link (to be sent by tom, apologies for the tight turn-around)

**ADDITIONAL CONTEXT:**
![image](https://github.com/user-attachments/assets/6d56e03d-e6b6-4e5e-bf8e-27c431ee5dc6)

## Issue Creator Checklist

- [ ] Fill out the relevant Title, Copy, Due Date, and Detail needs from
      #communications channel into the description.

- [ ] Ensure that the graphic from #communications or #graphics is attached.

- [ ] On the GitHub Issues sidebar, set the "Project" to "Metro Support
      Rotations"

- [ ] Ping the assigned team member in the thread in the #digitech-github Slack
      channel!

## Assignee Checklist

- [ ] Update `event` document in Sanity and deploy

- [ ] After deploy is published, verify that event card is visible on homepage
      tiles and `/events` (as applicable)

**Comment by paulhchoi** [comment]
finished up and deploying 🙌
