### ISSUE TITLE
Request: EF & CH: Crossroads Children's Fellowship's "Metro Monster Mash" (Saturday, October 26, 3:00PM-5:00PM):

### ISSUE THREAD

**Issue by jessxu12** [metrophilly/docs.metrophilly.org#135]
Fill out event details (Usually comes from the #communications slack channel)

**TITLE:**
EF & CH: Crossroads Children's Fellowship's "Metro Monster Mash" (Saturday, October 26, 3:00PM-5:00PM):

**COPY:**
EF & CH's 9/29 bulletin copy: "Calling all Metro Monsters (and their family and friends)! Crossroads Children’s Fellowship is hosting our first Trunk-or-Treat event this fall. Put on your costumes and join us for some fun festivities on Saturday, October 26, 2024, from 3:00PM–5:00PM at our Cherry Hill campus (5 Carnegie Plaza, Cherry Hill, NJ 08003). In case of rain, the event will be held on Saturday, November 2, 2024. Register at http://metrophilly.org/events and reach out to tina@metrophilly.org with any questions."

**DUE DATE:**
on site by Sat 9/28 with registration link: https://form.jotform.com/242685367387068 

**ADDITIONAL CONTEXT:**
![image](https://github.com/user-attachments/assets/d094b287-5273-4723-a7cb-55d1e6dbe9d4)

## Issue Creator Checklist

- [ ] Fill out the relevant Title, Copy, Due Date, and Detail needs from
      #communications channel into the description.

- [ ] Ensure that the graphic from #communications or #graphics is attached.

- [ ] On the GitHub Issues sidebar, set the "Project" to "Metro Support
      Rotations"

- [ ] Ping the assigned team member in the thread in the #digitech-github Slack
      channel!

## Assignee Checklist

- [ ] Update `event` document in Sanity and deploy

- [ ] After deploy is published, verify that event card is visible on homepage
      tiles and `/events` (as applicable)

**Comment by jessxu12** [comment]
Sorry just realized I forgot to attach the graphic

**Comment by paulhchoi** [comment]
reviewed and set, closing 👍
