### ISSUE TITLE
Request: CH Only: "Young Adult Picnic" (Sunday, June 8, 1:00PM-3:00PM):

### ISSUE THREAD

**Issue by jessxu12** [metrophilly/docs.metrophilly.org#33]
Fill out event details (Usually comes from the #communications slack channel)

**TITLE:**
CH Only: "Young Adult Picnic" (Sunday, June 8, 1:00PM-3:00PM):

**COPY:**
"All Young Adults in the South Jersey area are invited to our Summer Picnic hosted at John Connolly Park (605 Centennial Blvd, Voorhees, NJ 08043) on Saturday, June 8th from 1:00PM to 3:00PM. Come hungry to connect with others, eat lunch, and get to know more about our church! Food will be provided. Contact brian@metrophilly.org with any questions."

**DUE DATE:**
on website by 5/18, no registration link

**ADDITIONAL CONTEXT:**
![image](https://github.com/metrophilly/docs.metrophilly.org/assets/169205889/3b25d303-0d84-4506-b825-2f4df67a9853)

## Issue Creator Checklist

- [x] Fill out the relevant Title, Copy, Due Date, and Detail needs from
      #communications channel into the description.

- [x] Ensure that the graphic from #communications or #graphics is attached.

- [x] On the GitHub Issues sidebar, set the "Project" to "Metro Support
      Rotations"

- [x] Ping the assigned team member in the thread in the #digitech-github Slack
      channel!

## Assignee Checklist

- [x] Update `event` document in Sanity and deploy

- [x] After deploy is published, verify that event card is visible on homepage
      tiles and `/events` (as applicable)

**Comment by jessxu12** [comment]
Photo attached!

**Comment by paulhchoi** [comment]
@jessxu12 ready to review!

**Comment by jessxu12** [comment]
Looks great, thanks!
