### ISSUE TITLE
Request: EF & CH: Gospel Academy Summer 2024 MACE Course Offering: "Biblical Theology: Overview and Serpentine Imagery" (Beginning Sunday, June 2):

### ISSUE THREAD

**Issue by jessxu12** [metrophilly/docs.metrophilly.org#39]
Fill out event details (Usually comes from the #communications slack channel)

**TITLE:**
EF & CH: Gospel Academy Summer 2024 MACE Course Offering: "Biblical Theology: Overview and Serpentine Imagery" (Beginning Sunday, June 2):

**COPY:**
"Please consider our new Metro Adult Christian Education (MACE) course offering, "Biblical Theology: Overview and Serpentine Imagery", beginning Sunday, June 2 at 1:15PM held on the Third Floor of our East Falls Campus but open to attendees of either campuses. Registration, course description, and dates (3-4 sessions) are available at http://metrophilly.org/academy at no cost but with limited space. Reach out to contact@metrophilly.org with any questions."

**DUE DATE:**
on website by Sat, 5/18 with registrations live by Tues, 5/21 (or earlier)

**ADDITIONAL CONTEXT:**
these graphics are for if and when reg is live by sunday; if not, i'll send yall a diff set of graphics by tom
![image](https://github.com/metrophilly/docs.metrophilly.org/assets/169205889/23991b52-9d99-4aca-859c-52b5d086a394)

## Issue Creator Checklist

- [x] Fill out the relevant Title, Copy, Due Date, and Detail needs from
      #communications channel into the description.

- [x] Ensure that the graphic from #communications or #graphics is attached.

- [x] On the GitHub Issues sidebar, set the "Project" to "Metro Support
      Rotations"

- [x] Ping the assigned team member in the thread in the #digitech-github Slack
      channel!

## Assignee Checklist

- [x] Update `event` document in Sanity and deploy

- [x] After deploy is published, verify that event card is visible on homepage
      tiles and `/events` (as applicable)

**Comment by paulhchoi** [comment]
@13jkim i'll handle this one as i have to create the registration for the classes and stuff too

**Comment by paulhchoi** [comment]
@jessxu12 ready to review!

**Comment by jessxu12** [comment]
Looks good!
