### ISSUE TITLE
[6/9/2024] Support: 🎥 Sermon Video Process & Upload

### ISSUE THREAD

**Issue by ellisPae** [metrophilly/docs.metrophilly.org#49]
**This is to ensure the sermon-only video is clipped, processed, and deployed to Youtube and the website.**

**Due: 6/11/2024 (Tuesday) 11 PM**

---

### Guide for working on this task:

- Clone and run the script at [https://github.com/metrophilly/sermon-processor](https://github.com/metrophilly/sermon-processor)

- Walkthrough TBD

### Checklist

- [x] Process and review the sermon video
- [x] Create Canva card with "SERMON Card" template
- [x] Upload video into YouTube & attach canva card
- [x] Update the "Sermon" document in Sanity to include the correct YouTube ID and deploy
- [x] Place the sermon in the correct playlist (e.g. "Our Functional Doctrines") and ensure that the playlist is in chronological order
- [x] When complete, shift card to "Ready to Review" and tag @ellisPae @jessxu12

**Comment by paulhchoi** [comment]
❤ thanks for adding these, ellis!

**Comment by dhy6785** [comment]
@ellisPae @jessxu12 @paulhchoi 

first time doing this. hopefully everything checks out!
