### ISSUE TITLE
Request: CH Only: "Metro Cherry Hill Picnic" (Saturday, September 21, 12:00PM-3:00PM)

### ISSUE THREAD

**Issue by jessxu12** [metrophilly/docs.metrophilly.org#68]
Fill out event details (Usually comes from the #communications slack channel)

**TITLE:**
CH Only: "Metro Cherry Hill Picnic" (Saturday, September 21, 12:00PM-3:00PM):

**COPY:**
"Metro invites you, your friends, and your family to our annual Fall picnic on Saturday, September 21 at Laurel Acres (1045 S Church St, Mt Laurel, NJ 08054) from 12:00PM-3:00PM. Please register and sign-up for food at http://metrophilly.org/events. Contact brian@metrophilly.org with any questions."

**DUE DATE:**
on website by Sat, 8/24 with registration link: https://metro817449.typeform.com/to/waUXDqhQ

**ADDITIONAL CONTEXT:**
![image](https://github.com/user-attachments/assets/984cc358-81d4-46ed-9d41-028348c22310)

## Issue Creator Checklist

- [x] Fill out the relevant Title, Copy, Due Date, and Detail needs from
      #communications channel into the description.

- [x] Ensure that the graphic from #communications or #graphics is attached.

- [x] On the GitHub Issues sidebar, set the "Project" to "Metro Support
      Rotations"

- [x] Ping the assigned team member in the thread in the #digitech-github Slack
      channel!

## Assignee Checklist

- [ ] Update `event` document in Sanity and deploy

- [ ] After deploy is published, verify that event card is visible on homepage
      tiles and `/events` (as applicable)

**Comment by ellisPae** [comment]
@paulhchoi @jessxu12 
Any update on the graphic?

**Comment by jessxu12** [comment]
> @paulhchoi @jessxu12 
> Any update on the graphic?

Sorry just saw this! Nah not yet, usually doesn’t come out until a day or two before due

**Comment by jessxu12** [comment]
@ellisPae just attached the graphic!
