### ISSUE TITLE
Request: EF Only: "Monthly Prayer Meeting" (Beginning 10/15, 6-7PM; 11/19, 6-7PM, 1/14, 6-7PM)

### ISSUE THREAD

**Issue by jessxu12** [metrophilly/docs.metrophilly.org#77]
Fill out event details (Usually comes from the #communications slack channel)

**TITLE:**
EF Only: "Monthly Prayer Meeting" (Beginning 10/15, 6-7PM; 11/19, 6-7PM, 1/14, 6-7PM)

**COPY:**
"You're invited to join us for our monthly prayer service beginning Tuesday, October 15 from 6:00PM-7:00PM at our East Falls Campus. This is open to anyone who wants to spend time praying for renewal—for themselves, others, our church, and our city. Contact brian@metrophilly.org with any questions"

**DUE DATE:**
on website by Sat 9/28, no registration link

**ADDITIONAL CONTEXT:**
Graphic to come by 9/27

## Issue Creator Checklist

- [x] Fill out the relevant Title, Copy, Due Date, and Detail needs from
      #communications channel into the description.

- [ ] Ensure that the graphic from #communications or #graphics is attached.

- [x] On the GitHub Issues sidebar, set the "Project" to "Metro Support
      Rotations"

- [ ] Ping the assigned team member in the thread in the #digitech-github Slack
      channel!

## Assignee Checklist

- [ ] Update `event` document in Sanity and deploy

- [ ] After deploy is published, verify that event card is visible on homepage
      tiles and `/events` (as applicable)

**Comment by paulhchoi** [comment]
pastor brian just told us this is getting postponed until January 2025, I'll close this for now and we can we-work this with a new ticket when the comms team lets us know about it again.
